export const EventOnApplicationReady = 'bubblesApplicationReady'
export const EventOnBridgeReady = 'bubblesSystemBridgeReady'
export const EventOnVersionReady = 'versionReadyEvent'
export const EventOnReady = 'bubblesBridgeReady'
export const EventBeforeOnReady = 'beforeBubblesBridgeReady'
